base_config: ../config/xdeepfm_criteo_x4/
base_expid: xDeepFM_criteo_x4
dataset_id: criteo_x4

tuner_space:
    embedding_dim: 16
    learning_rate: 1.e-3
    dnn_hidden_units: [[500,500,500,500,500]]
    cin_layer_units: [[64, 64, 64], [64, 64]]
    net_dropout: 0.2
    embedding_regularizer: [1.e-4, 1.e-3]
    batch_size: [10000]
    seed: 2019
    debug_mode: False
 